### ISSUE TITLE
Browserify transform request

### ISSUE THREAD

**Issue by peacechen** [StoryCloud/webkit-assign#5]
I'd like to request a browserify transform to apply this fix to the code during bundling.  Anyone else interested please leave a comment.  Is it ok to use the code in webkit-assign in another project?

**Comment by jacksonrayhamilton** [comment]
webkit-assign is available under the [MIT License](https://github.com/StoryCloud/webkit-assign/blob/master/LICENSE.txt); it is okay for you to use it in other projects, provided you adhere to that license's terms.

If you're up to it, you could submit a PR providing a browserify transform.

**Comment by peacechen** [comment]
Writing a Browserify transform turns out to be straight-forward.  It calls the module with a filename, and expects a stream returned.  Fortunately webkit-assign already supports streams with webkitAssignStream().  I added a Browserify transform wrapper and updated the Readme.  See the pull request for details.

**Comment by peacechen** [comment]
Updated the PR as requested by ccamarat.  What's the timeline for reviewing & merging it, and publishing on npm?  Hoping to use this in our project.

**Comment by jacksonrayhamilton** [comment]
`v1.3.0` is now available on npm, and includes the transform.

**Comment by peacechen** [comment]
:thumbsup:
